version: '3'

networks:
  app-network:
    driver: bridge

services:
  app:
    container_name: CrudService
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    env_file:
      - .env


  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network
