version: '3'

networks:
  app-network:
    driver: bridge

services:
  app:
    container_name: CrudService
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network


  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
