version: '3'

networks:
  network:
    driver: bridge

services:
  app:
    container_name: CrudService
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - network
    env_file:
      - .env`

  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - network

  redis:
    container_name: redis
    image: redis:6.0.0
    restart: always
    ports:
      - "6379:6379"
    networks:
      - network
    command: redis-server --save 20 1

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - network
